### ISSUE TITLE
dW Answers is gone.

### ISSUE THREAD

**Issue by cncook001** [ibm-cloud-docs/security-advisor#176]
Bottom of this page https://cloud.ibm.com/docs/security-advisor?topic=security-advisor-getting-started

"You can also send user feedback by using dW Answers to contribute ideas for the service as it develops."

-> There should be a new place to send feedback

**Comment by smguilia** [comment]
Hi @cncook001,

Thank you for opening feedback. I've removed the statement from the getting started page. You can use the information in getting help and support to send feedback. https://test.cloud.ibm.com/docs/security-advisor?topic=security-advisor-troubleshooting

Please don't hesitate to open an issue in the future. I'm always looking for ways to make the docs better.
- Shawna
